# Arrays in Numpy

Topics covered in this post:

- nd-array
- Array Terminologies
- Uses of arrays
- how to create array
- Basic Array Operations (Elementwise operations)
    - Binary operations: A calculation that combines two elements/operands to produce a single result.
        - Addition, Subtraction, Multiplication, Division
    - Unary operations: A calculation that uses one element/operand to produce a single output.
        - Reciprocal, Negation

**What is an array?**

An array is a data structure meant to hold data in a particular structure. Formal definition as per the numpy docs is as follows:

> An array object represents a multidimensional, homogeneous array of fixed-size items.

For understanding the definition, we have to first understand all the terms mentioned here. So, let's start with some intuition from geometry to understand the concept of what dimensions are.

In geometry, fundamental unit/building block is a point which is a zero-dimensional entity. When they're arranged next to each other, we get a contiguous set of points making a line; this is a one-dimensional entity. 

Next, when we arrange a set of lines which are at some angle (other than 0 degrees) to one another, we get a plane which is a two dimensional entity and then sets of planes which define a parallelopiped become a three dimensional entity and so on. Since we're three-dimensional beings, we can visualize 0, 1, 2 and 3-Dimensional structures but this logic of stacking dimensions can continue perpetually and we call the resulting space n-dimensional space.

*The nd-array object in numpy can be thought of a generic object capable of representing data in n-dimensions. You can think of a python list as one dimension. When you nest multiple lists within one another, you create what is an n-dimensional array. (n-dimensional is just another way of saying multi-dimensional).*

Now that we have some idea of what a dimension is, let's tackle the second part. *Homogeneous* simply means that the lists which we nest to create this structure must all contain same kind of items. 

Let's say you have a box of oranges with oranges aligned neatly with their axes perpendicular to each other. This arrangement is a 3-Dimensonal one. However if you got an apple sitting in one or more spots in this box, you can't call this arrangement a 3-Dimensional array. Note that it cannot be called an array because you have dissimilar items in the arrangement. That's what homogenous means.

In terms of program, a nested list could be called an array if all elements of all lists are of the same datatype i.e. either int, float, bools, strings or anything. But since we're doing numerical computation, these types are limited to ints and floats for numpy.

## Array Terminologies

**Rank of an array**

The rank of an array is the number of dimensions present within the array. It's interesting to note that some arrays have also got special names.

A rank one array is also called a vector, just an array. (Colloquil understanding is that array = 1 dimension).

A rank two array is also called a matrix.

All other arrays are referred to by prepending the rank followed by a D. eg. 3D-array, 4D-array, nD-array etc.

**Axis of an array**

The axis of an array is a specific dimension along that array. The elements of an array are said to run along/across axis of an array. The length of an axis is the number of elements running along that axis.

**Shape of an array**

The lengths of all the axis together correspond to the shape of an array. If we know the shape of an array, we automatically know the rank and axes as well. 

For eg. a 3 X 4 array has rank 2 and the there are two axes which run for a length of 3 and 4 elements respectively.

## Uses of array
Now that we know about what arrays are, let's first understand how & where they're useful and then go on to study them in more depth.

To name a few uses of arrays, they're as follows:

- Any Machine Learning problem involves expressing the output Y as a function of the input X. These inputs and outputs are expressed typically as a 1-Dimensional array or more colloquially referred to as vectors. 

- Applications involving checking the states of machines/elements/programs use flags or flag variables which are convenient to be represented as vectors.

- In any natural language processing problem, sentences are represented as sequence of words. A sequence of words is nothing but a 1-D array/vector. Also in time-series analysis, the dependent variable is studied with respect to it's past values which are also represented as a 1-Dimensional array/vector.

- Images are represented as either 2-Dimensional (monochromatic) or 3-Dimensional (colored) or 4-Dimensional (colored with transparency) arrays of numbers. Any Deep Learning application needs you to specify the image in one of these formats. What you're viewing on your screen right now as you read this is a 3-Dimensional/4-Dimensional array being rendered as an image in real-time; that's how important and underappreciated this data-structure called as an array is!

Now that we know why we need arrays, let's get our hands dirty and understand how we can use them.

## Creating an array in numpy

It's simple to create an array in numpy. You create a list and wrap numpy's array function around it as follows

```python
import numpy as np
x = [1, 2, 3, 10, 11]
y = np.array(x)
```

Optionally you can specify the type of data you want your numpy array to be. It could be one of np.int8, np.int16, np.int32, np.int64, np.float16, np.float32, np.float64. The numbers specify the number of bits used to store every element in that array. If you don't specify, numpy will automatically assign one of np.int64 or np.float64 based on the data you have in the array.

You can see the shape of an array using
```python
print(np.shape(x))
```

This prints the shape of the array x to the console. Also you can see the rank of an array using
```python
print(len(np.shape(x))
```
since shape is basically a tuple with the lengths of axes. 


## Elementwise Array Operations

In [1]:
import numpy as np

In [2]:
# Defining an array using list of lists
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [3]:
# Adding two arrays
x + y

array([[ 6,  8],
       [10, 12]])

In [4]:
# Subtracting one array from another
x - y

array([[-4, -4],
       [-4, -4]])

In [5]:
# Multiplying one array to another
x * y

array([[ 5, 12],
       [21, 32]])

In [6]:
# Dividing one array with another
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [7]:
# Unary - Reciprocal of an array
1 / x

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

In [8]:
# Unary - Negation of an array
-y

array([[-5, -6],
       [-7, -8]])

In [9]:
import numpy as np
np.random.seed(10)
y = np.random.random((5, 5))
print(y)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]]
